-- name: \\#ffff1e\\Coords \\#ff00ff\\Better\\#00ff00\\ + \\#dcdcdc\\[WIP]
-- description: Una revolucion de los mods de utilidad. Se tomaron ideas de varios mods, mas notablemente el modo de juego \\#3df5ff\\Flood \\#00ff00\\+\\#dcdcdc\\ y de algunos mods de un desarrollador llamado\n\\#9b9b9b\\Agent \\#ec7731\\X\\#dcdcdc\\, de ellos se tomaron ideas y se aprendio de sus mods, para hacer este increible mod.\nPuedes consultar los comandos del mod al escribir "/help" en el chat.\n\n \\#1892f5\\Creado por\\#dcdcdc\\: el equipo de devs de\n\ \\#ffa700\\Coords Better\\#dcdcdc\\.\n\n--------------------------------\n-\\#00ff00\\Version: 1.4.1\\#dcdcdc\\-\n--------------------------------
-- category: utility
-- deluxe: true
